### PR TITLE
MT-71 Removes the Travis CI configuration file. All CI targets are mi…

### PR DESCRIPTION
**Pull request by gnrunge**
…grated.

### CODE REVIEW

**Comment by gnrunge** [comment]
Target ruby-latest-jruby worked a at the last commit a few days ago. Failure of the ruby-latest-jruby target is reproducible in a separate branch. No failure when using plain 'ruby-version: jruby' only, which I'd assume is the default version but most likely not the latest version. Any idea what is going on. It say 'bundle: command not found' (from 'install bundle').

**Comment by gnrunge** [comment]
Looks like one has to explicitly install the bundler: 'gem install bundler'.

**Comment by sffc** [comment]
Hmm.  I don't know what's going on with jruby.  The CI says specifically that bundler is installed:

```
Installing Bundler
  Using Bundler 2 shipped with jruby-head
  Took   0.00 seconds
```

**Review by echeran — APPROVED** [review]
LGTM.

Good find on the need to run `gem install bundler`. I guess that makes sense. (I suppose it all depends on which languages and/or build tools come pre-installed on the VM and/or by the extra relevant Github Actions we invoke.)

**Comment by gnrunge** [comment]
> LGTM.
> 
> Good find on the need to run `gem install bundler`. I guess that makes sense. (I suppose it all depends on which languages and/or build tools come pre-installed on the VM and/or by the extra relevant Github Actions we invoke.)

I added 'gem install bundler' just now and squashed it in to the pull request. All the MT CI targets now passing, waiting for fuzzer CI to finish.

**Review by echeran — APPROVED** [review]
still LGTM!

**Review by sffc — APPROVED** [review]

**Pull request merged**
